version: '3.8'

services:
  eureka-service:
    image: openjdk:17-jdk-slim
    container_name: sm-eureka-service
    ports:
      - "8761:8761"
    volumes:
      - ./sm-eureka-service/target/sm-eureka-service-0.0.1-SNAPSHOT.jar:/app/sm-eureka-service.jar   # Ajusta la ruta al JAR
    working_dir: /app
    command: ["java", "-jar", "sm-eureka-service.jar"]

  api-gateway:
    image: openjdk:17-jdk-slim
    container_name: sm-api-gateway
    ports:
      - "9090:9090"
    volumes:
      - ./sm-api-gateway/target/sm-api-gateway-0.0.1-SNAPSHOT.jar:/app/sm-api-gateway.jar  # Ajusta la ruta al JAR
    working_dir: /app
    command: ["java", "-jar", "sm-api-gateway.jar"]

  ms-api-clientes:
    image: openjdk:17-jdk-slim
    container_name: ms-api-clientes
    ports:
      - "8081:8080"
    volumes:
      - ./ModuloClientePersona/target/ModuloClientePersona-0.0.1-SNAPSHOT.jar:/app/ModuloClientePersona.jar  # Ajusta la ruta al JAR
    working_dir: /app
    command: ["java", "-jar", "ModuloClientePersona.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/baseprueba
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root12345

  ms-cuenta-movimiento:
    image: openjdk:17-jdk-slim
    container_name: ms-cuenta-movimiento
    ports:
      - "8082:8080"
    volumes:
      - ./ModuloCuentaMovimiento/target/ModuloCuentaMovimiento-0.0.1-SNAPSHOT.jar:/app/ModuloCuentaMovimiento.jar  # Ajusta la ruta al JAR
    working_dir: /app
    command: ["java", "-jar", "ModuloCuentaMovimiento.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/baseprueba
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root12345

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
        - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root12345
      MYSQL_DATABASE: baseprueba
    volumes:
      - mysql_data:/var/lib/mysql

  zookeeper:
    image: zookeeper:3.6
    ports:
      - "2182:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9093:9092"  # Cambié el puerto a 9093 para evitar conflictos
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

volumes:
  mysql_data:
